[book]
authors = ["Lucy Vin"]
description = "A rules-lite(ish) tabletop RPG for SCP related campaigns"
language = "en"
multilingual = false
src = "src"
title = "Warped World: An SCP Tabletop Roleplaying Game"

[output.html]
default-theme = "wanderer"
